### ISSUE TITLE
Move to GitHub actions

### ISSUE THREAD

**Issue by nfrerebeau** [crp2a/BayLum#15]
BayLum currently uses the third-party CI services Travis and Appveyor. Would it be possible to use GitHub Actions instead? This would reduce the number of services to manage by bringing everything under one roof.

**Comment by RLumSK** [comment]
Possibly, I had a look into it, but for the moment, I would refrain from transferring projects. I admit that managing TRAVIS and AppVeyor had a little bit messy in the past. However,  it still also uncovered a lot of flaws in the code across platforms. So, as long as it works, I would not change the running system.

**Comment by RLumSK** [comment]
TRAVIS CI abandoned us, we abandon TRAVIS CI ... besides, it was a very good service over the years, but it is no more.
